################################################################################
## APPROACH 4: Literature Review and Signature Comparison
##
## Strategy: Search for existing menopause gene signatures in literature
## Compare with our results to identify robust menopause markers
################################################################################
# Ensure a default CRAN mirror is set for non-interactive runs
.repos <- getOption("repos")
.cran <- unname(.repos["CRAN"])
if (is.null(.cran) || is.na(.cran) || .cran == "@CRAN@" || .cran == "") {
  options(repos = c(CRAN = "https://cloud.r-project.org"))
}
rm(.repos, .cran)


if (!requireNamespace("pacman", quietly = TRUE)) install.packages("pacman")
pacman::p_load(
  data.table, readr, dplyr, tidyr, stringr, tibble, purrr, glue, magrittr,
  ggplot2, patchwork
)

source("R/utils.R")

## -----------------------------------------------------------------------------
## Setup
## -----------------------------------------------------------------------------
out_dir  <- "GTEx_v10_AT_analysis_out"
fig_dir  <- file.path(out_dir, "figs", "approach4_literature")
tab_dir  <- file.path(out_dir, "tables", "approach4_literature")
ensure_dirs(c(out_dir, fig_dir, tab_dir))

cat("\n===========================================\n")
cat("APPROACH 4: LITERATURE REVIEW & SIGNATURE COMPARISON\n")
cat("===========================================\n\n")

## -----------------------------------------------------------------------------
## Known menopause-related gene sets from literature
## -----------------------------------------------------------------------------
cat("Compiling known menopause signatures from literature...\n\n")

## General hormone / ovarian axis markers (seed list; edit as needed)
general_menopause_markers <- c(
  "ESR1", "ESR2", "PGR",
  "CYP19A1", "HSD17B1", "HSD17B2",
  "FSHR", "LHCGR", "FSHB", "LHB",
  "AMH", "INHA", "INHBA", "FOXL2", "BMP15", "GDF9"
)

## Optional: load GSE86244 age-proxy DE gene lists if available.
## These are generated by `R/validate_with_gse86244_counts_age_proxy.R`.
gse_tab_dir <- file.path(out_dir, "tables", "gse86244_validation_counts_age_proxy")
gse_up_path <- file.path(gse_tab_dir, "GSE86244_post_up_gene_symbols.txt")
gse_down_path <- file.path(gse_tab_dir, "GSE86244_post_down_gene_symbols.txt")

gse_age_proxy_union <- character(0)
if (file.exists(gse_up_path) && file.exists(gse_down_path)) {
  gse_up <- readr::read_lines(gse_up_path) %>% stringr::str_trim() %>% toupper()
  gse_down <- readr::read_lines(gse_down_path) %>% stringr::str_trim() %>% toupper()
  gse_up <- gse_up[nzchar(gse_up)]
  gse_down <- gse_down[nzchar(gse_down)]
  gse_age_proxy_union <- unique(c(gse_up, gse_down))
  cat(sprintf("Loaded GSE86244 age-proxy gene lists: up=%d, down=%d\n", length(gse_up), length(gse_down)))
} else {
  cat("Note: GSE86244 age-proxy gene lists not found; run the validation script to generate them.\n")
}

## Combine all known signatures (seed lists)
all_known_signatures <- list(
  General_menopause_seed = general_menopause_markers,
  GSE86244_age_proxy_union = gse_age_proxy_union
)

## -----------------------------------------------------------------------------
## Load our DE results (from Approach 1)
## -----------------------------------------------------------------------------
cat("Loading our DE results from Approach 1...\n")

approach1_tab_dir <- file.path(out_dir, "tables", "approach1_improved_age_proxy")
our_results_path <- file.path(approach1_tab_dir, "DE_menopause_proxy_improved.tsv")
if (file.exists(our_results_path)) {
  our_results <- readr::read_tsv(our_results_path, show_col_types = FALSE)

  cat(sprintf("Loaded %d genes from our analysis\n", nrow(our_results)))

  ## Check overlap with known signatures
  cat("\nChecking overlap with known menopause signatures...\n")

  overlap_summary <- bind_rows(lapply(names(all_known_signatures), function(sig_name) {
    sig_genes <- all_known_signatures[[sig_name]]

    overlap_count <- sum(our_results$gene_symbol %in% sig_genes)
    sig_overlap_count <- sum(our_results$gene_symbol %in% sig_genes &
                              our_results$significant == "TRUE")

    tibble::tibble(
      signature = sig_name,
      signature_size = length(sig_genes),
      overlap = overlap_count,
      sig_overlap = sig_overlap_count
    )
  }))

  print(overlap_summary)

  ## Find genes that are in known signatures AND our DE results
  our_results$in_general <- our_results$gene_symbol %in% general_menopause_markers
  our_results$in_gse86244_age_proxy <- if (length(gse_age_proxy_union)) {
    our_results$gene_symbol %in% gse_age_proxy_union
  } else {
    FALSE
  }

  ## Save comparison
  readr::write_tsv(
    our_results %>%
      arrange(padj) %>%
      dplyr::select(gene_symbol, log2FoldChange, padj, significant, in_general, in_gse86244_age_proxy) %>%
      head(1000),
    file.path(tab_dir, "signature_comparison.tsv")
  )

  cat(sprintf("Saved comparison to: %s\n", file.path(tab_dir, "signature_comparison.tsv")))

} else {
  cat("Our DE results not found yet.\n")
  cat("Run Approach 1 first, then this script will compare results.\n")
  our_results <- NULL
}

## -----------------------------------------------------------------------------
## Create literature summary document
## -----------------------------------------------------------------------------
cat("\nCreating literature summary document...\n")

lit_summary <- paste0(
  "# Menopause Gene Signatures: Literature Review\n\n",
  "## Known Signatures from Literature\n\n",
  "### 1. GSE86244 (RNA-seq; GEO supplementary counts)\n",
  "- Dataset: GSE86244\n",
  "- Notes: count matrices are provided as GEO supplementary files.\n",
  "- This repo's pipeline uses an age proxy (pre <45 vs post >55) and writes gene lists under:\n",
  "  ", gse_tab_dir, "\n\n",
  "### 2. General hormone/ovarian axis markers (seed list)\n",
  "- Hormone receptors: ESR1, ESR2, PGR\n",
  "- Steroidogenesis: CYP19A1, HSD17B1, HSD17B2\n",
  "- Ovarian axis: AMH, INHA/INHBA, FOXL2, BMP15, GDF9\n\n",
  "## Recommendations\n\n",
  "1. **Literature-derived component**: use the repo's GSE86244 age-proxy DE lists as a cross-check\n",
  "   - Menopause is not explicitly labeled in GEO metadata here; treat as supportive only\n",
  "   - Cell context differs from whole adipose\n\n",
  "2. **Secondary validation**: Cross-reference with general markers\n",
  "   - ESR1/ESR2/PGR should show changes\n",
  "   - Look for enrichment in hormone pathways\n\n",
  "3. **Gene refinement**: Remove obvious cell-type / contamination markers\n",
  "   and keep a curated, versioned list (see references/menopause_signature_curated.tsv)\n\n",
  "## Proposed Menopause Signature Gene Set\n\n",
  "Based on literature seed markers, prioritize:\n",
  "1. Hormone-responsive genes (ESR1, ESR2, PGR)\n",
  "2. Steroidogenesis (CYP19A1, HSD17B*)\n",
  "3. Ovarian axis markers (AMH, INHA/INHBA, FOXL2)\n\n",
  "---\n",
  "Generated: ", Sys.time(), "\n"
)

writeLines(lit_summary, file.path(tab_dir, "literature_review.md"))

cat(sprintf("Saved literature review to: %s\n", file.path(tab_dir, "literature_review.md")))

## -----------------------------------------------------------------------------
## Summary
## -----------------------------------------------------------------------------
cat("\n===========================================\n")
cat("APPROACH 4: SUMMARY\n")
cat("===========================================\n\n")

cat("Literature-based signatures compiled:\n")
for (sig_name in names(all_known_signatures)) {
  cat(sprintf("  - %s: %d genes\n", sig_name, length(all_known_signatures[[sig_name]])))
}

cat("\nKey findings from literature (high-level):\n")
cat("  1. Hormone pathways (estrogen/progesterone) central\n")
cat("  2. Public datasets may require phenotype reconstruction\n")
cat("  3. Cell-type and cohort differences can dominate\n\n")

cat("Output files:\n")
cat(sprintf("  Literature review: %s\n", file.path(tab_dir, "literature_review.md")))
cat(sprintf("  Signature comparison: %s\n", file.path(tab_dir, "signature_comparison.tsv")))

cat("\nRecommended next steps:\n")
cat("  1. Review MSigDB estrogen-response proxy scoring (tables/msigdb_proxy_scoring)\n")
cat("  2. Iterate references/menopause_signature_curated.tsv\n")
cat("  3. Add additional labeled menopause cohorts from literature (if available)\n")

cat("===========================================\n\n")
